### PR TITLE
Add start and description to carbon bombs

### PR DESCRIPTION
**Pull request by gpenessot**
- Add start year and description from GEM or ChatGPT if no data is available.
- Add information source for both start year and description : GEM / ChatGPT

### CODE REVIEW

**Review by mnicolleUTC — APPROVED** [review]
PR approved, thanks for the contribution

**Review by mnicolleUTC — CHANGES_REQUESTED** [review]
Rebase must be reviewed

**Review by gpenessot — COMMENTED** [review]
ok

**Review by gpenessot — COMMENTED** [review]
ok with changes

**Comment by Nathanlauga** [comment]
rebase problem

**Pull request closed without merging**
